### ISSUE TITLE
Error with Port.add

### ISSUE THREAD

**Issue by Industrial** [am01264/types-noflo#1]
Hi.

Currently the third argument `process` of `Ports.add(name, options, process)` is mandatory and not optional, but in the API both the options and process arguments are optional.

I am now calling this like `component.inPorts.add('in', { datatype: 'string' }, component)` but I believe this to be unnecessary.

**Comment by Industrial** [comment]
I have more problems `component.process(async (input, output, context) => {})` This has a third argument which is not on the type.

**Comment by am01264** [comment]
Hi there,
Cheers for filing this. I'll be back with a fix later today.

**Comment by am01264** [comment]
That's it now published on NPM also.
Cheers for the feedback
