### ISSUE TITLE
Component demands you set Generic Types

### ISSUE THREAD

**Issue by am01264** [am01264/types-noflo#3]
Spotted in the wild as:

```typescript
export class DisplayOHLCV<
  Inports extends string,
  Outports extends string
> extends noflo.Component {

    // ...

}
```

As a types-only library, I would expect it to just work by default, and let me choose to restrict types if I'm willing to go down the generics rabbit hole. 

I would expect the following instead:

```typescript
export class DisplayOHLCV extends noflo.Component {

    // ...

}
```

**Comment by am01264** [comment]
@Industrial spotted this in a test project. 
Hopefully this is the last major surprise for you.

**Comment by Industrial** [comment]
@am01264 I'm just playing with the FBP concepts. Currently I am working on https://github.com/Industrial/deno-fbp which will be a FBP runtime for Deno made with TypeScript. I am nowhere near anything yet and I just have a basic structure of the classes working / tested.

I hope at some point it can support the FBP protocol but I'm not in a hurry ;)
