### ISSUE TITLE
NoFlo asCallback can also accept a fbp-graph.Graph instance

### ISSUE THREAD

**Issue by bergie-umi** [am01264/types-noflo#7]
Right now the type definition for NoFlo.asCallback has been defined as either a string or a Component. Actually it should either be a component _name_, or a Graph instance. The latter case can be seen in action here:

https://github.com/noflo/noflo/blob/master/spec/AsCallback.js#L348

**Comment by am01264** [comment]
I'll sort this now.
I must confess I wrote this almost entirely reading the source & experimentation, I hadn't thought to read the tests 🤦‍♂️

Cheers

**Comment by bergie-umi** [comment]
No worries, I was super happy to find that this exists!
